### ISSUE TITLE
Request: WebLikertImageElement

### ISSUE THREAD

**Issue by kangaroo07** [ctreffe/alfred-public#1]
Dear alfred-host, 

since many tasks require a choice between more than two elements, it would be very useful to have an ImageElement which supports a single choice between x pictures e.g. a matrix reasoning task where a choice between five or more alternatives must be made. It would be great to have such an element in the repository. Thank you!

Best regards
kangaroo07

**Comment by ctreffe** [comment]
This should already be possible with alfred's standard single choice element, since pictures can be inserted instead of itemlabels using the html image tag. However, layouting the pictures any other way than in a vertical row would require either a new element or a combination of single choice elements within a table element.

I think we should derive a new element from LikertMatrix() which will contain only a single radiobutton group instead of multiple groups. This way the element could both be used with labels or images. From this SingleChoiceMatrix() we could easily derive a SingleChoiceImageMatrix(), replacing the radiobuttons with clickable images.

I will transfer this request with the suggested solution to alfred's internal development repository.
